export const DANIEL_CARTER_FIXTURE = {
  testator: {
    fullName: "Daniel Michael Carter",
    arabicName: "دانيال مايكل كارتر",
    dob: "1984-06-15",
    nationality: "British",
    passportNumber: "GB12345678",
    emiratesId: "784-1984-1234567-1",
    isUaeResident: true,
    residentialAddress: "Apartment 1402, Marina Crown Tower, Dubai Marina, Dubai, UAE",
    emailAddress: "daniel.carter@example.com",
    contactNumber: "+971 50 123 4567",
    domicileCountry: "England and Wales",
  },
  executors: [
    {
      partyType: "PRIMARY_EXECUTOR" as const,
      fullName: "Sarah Elizabeth Carter",
      arabicName: "سارة إليزابيث كارتر",
      isArabicApproved: true,
      dob: "1988-03-20",
      nationality: "British",
      passportNumber: "GB55443322",
      emiratesId: "",
      isUaeResident: false,
      address: "14 Kensington Gardens, London W8 4PT, United Kingdom",
      email: "sarah.carter@example.co.uk",
      phone: "+44 7700 900123",
    },
    {
      partyType: "SUBSTITUTE_EXECUTOR" as const,
      fullName: "James Robert Carter",
      arabicName: "جيمس روبرت كارتر",
      isArabicApproved: true,
      dob: "1991-11-05",
      nationality: "British",
      passportNumber: "GB66778899",
      emiratesId: "",
      isUaeResident: false,
      address: "8 The Meadows, Cambridge CB2 1TJ, United Kingdom",
      email: "james.carter@example.co.uk",
      phone: "+44 7700 900456",
    },
  ],
  beneficiaries: {
    primary: {
      partyType: "PRIMARY_BENEFICIARY" as const,
      fullName: "Emma Claire Carter",
      arabicName: "إيما كلير كارتر",
      isArabicApproved: true,
      dob: "1986-09-22",
      nationality: "British",
      passportNumber: "GB87654321",
      emiratesId: "784-1986-7654321-2",
      isUaeResident: true,
      address: "Apartment 1402, Marina Crown Tower, Dubai Marina, Dubai, UAE",
      email: "emma.carter@example.com",
      phone: "+971 50 765 4321",
      sharePercentage: 100.0,
    },
    substitutes: [
      {
        partyType: "SUBSTITUTE_BENEFICIARY" as const,
        fullName: "Liam James Carter",
        arabicName: "ليام جيمس كارتر",
        isArabicApproved: true,
        dob: "2017-04-12",
        nationality: "British",
        passportNumber: "GB33445566",
        emiratesId: "784-2017-3344556-3",
        isUaeResident: true,
        address: "Apartment 1402, Marina Crown Tower, Dubai Marina, Dubai, UAE",
        email: "",
        phone: "",
        sharePercentage: 50.0,
      },
      {
        partyType: "SUBSTITUTE_BENEFICIARY" as const,
        fullName: "Noah Alexander Carter",
        arabicName: "نوح ألكسندر كارتر",
        isArabicApproved: true,
        dob: "2020-11-03",
        nationality: "British",
        passportNumber: "GB77889900",
        emiratesId: "784-2020-7788990-4",
        isUaeResident: true,
        address: "Apartment 1402, Marina Crown Tower, Dubai Marina, Dubai, UAE",
        email: "",
        phone: "",
        sharePercentage: 50.0,
      },
    ],
  },
  children: [
    {
      fullName: "Liam James Carter",
      arabicName: "ليام جيمس كارتر",
      dob: "2017-04-12",
      nationality: "British",
      passportNumber: "GB33445566",
    },
    {
      fullName: "Noah Alexander Carter",
      arabicName: "نوح ألكسندر كارتر",
      dob: "2020-11-03",
      nationality: "British",
      passportNumber: "GB77889900",
    },
  ],
  guardians: [
    {
      partyType: "PERMANENT_GUARDIAN" as const,
      fullName: "Sarah Elizabeth Carter",
      arabicName: "سارة إليزابيث كارتر",
      isArabicApproved: true,
      dob: "1988-03-20",
      nationality: "British",
      passportNumber: "GB55443322",
      address: "14 Kensington Gardens, London W8 4PT, UK",
      email: "sarah.carter@example.co.uk",
      phone: "+44 7700 900123",
    },
    {
      partyType: "TEMPORARY_GUARDIAN" as const,
      fullName: "David Alan Whitfield",
      arabicName: "ديفيد ألان ويتفيلد",
      isArabicApproved: true,
      dob: "1983-07-14",
      nationality: "British",
      passportNumber: "GB99001122",
      address: "Villa 42, Springs 11, Dubai, UAE",
      email: "david.whitfield@example.ae",
      phone: "+971 50 999 8877",
    },
  ],
  assets: [
    {
      assetType: "Immovable Property",
      description: "Apartment 1402, Marina Crown Tower, Dubai Marina",
      emirate: "Dubai",
      titleDeedNumber: "TD-2021-99882",
    },
    {
      assetType: "Bank Account",
      description: "Emirates NBD Current Account",
      emirate: "Dubai",
      titleDeedNumber: "AE290260000123456789012",
    },
  ],
};
